### ISSUE TITLE
Incompatibility with this mod and Enchanted Wolves

### ISSUE THREAD

**Issue by Mizhok** [cybercat5555/BetterAnimals#23]
https://www.curseforge.com/minecraft/mc-mods/enchanted-wolves

```Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Enchanted Wolves (enchantedwolves)
Caused by: java.lang.ClassCastException: com.ocelot.betteranimals.client.render.entity.RenderNewWolf cannot be cast to net.minecraft.client.renderer.entity.RenderWolf
	at com.javisel.enchantedwolves.proxy.ClientProxy.init(ClientProxy.java:55)
	at com.javisel.enchantedwolves.EnchantedWolves.init(EnchantedWolves.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1176145384 bytes (1121 MB) / 2177368064 bytes (2076 MB) up to 3008888832 bytes (2869 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 181 mods loaded, 181 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                          | Version              | Source                                             | Signature                                |
	|:----- |:--------------------------- |:-------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft                   | 1.12.2               | minecraft.jar                                      | None                                     |
	| LCHI  | mcp                         | 9.42                 | minecraft.jar                                      | None                                     |
	| LCHI  | FML                         | 8.0.99.99            | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCHI  | forge                       | 14.23.5.2847         | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCHI  | creativecoredummy           | 1.0.0                | minecraft.jar                                      | None                                     |
	| LCHI  | foamfixcore                 | 7.7.4                | minecraft.jar                                      | None                                     |
	| LCHI  | opencomputers|core          | 1.7.5.192            | minecraft.jar                                      | None                                     |
	| LCHI  | randompatches               | 1.12.2-1.21.0.0      | randompatches-1.12.2-1.21.0.0.jar                  | None                                     |
	| LCHI  | additionalbanners           | 1.1.77               | AdditionalBanners-1.12.2-1.1.77.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHI  | engineerstools              | 1.0.5                | engineerstools-1.12.2-1.0.5.jar                    | None                                     |
	| LCHI  | forgelin                    | 1.8.4                | Forgelin-1.8.4.jar                                 | None                                     |
	| LCHI  | baubles                     | 1.5.2                | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHI  | thaumcraft                  | 6.1.BETA26           | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
	| LCHI  | thaumic_arcana              | 1.2.0                | Thaumic Arcana-1.3.0.jar                           | None                                     |
	| LCHI  | jei                         | 4.15.0.293           | jei_1.12.2-4.15.0.293.jar                          | None                                     |
	| LCHI  | immersiveengineering        | 0.12-92              | ImmersiveEngineering-0.12-92.jar                   | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHI  | alternatingflux             | 0.12.2-2             | alternatingflux-0.12.2-2.jar                       | None                                     |
	| LCHI  | csb_armorstand              | 1.0.4                | ArmorStandGUI-1.12-1.0.4.jar                       | None                                     |
	| LCHI  | carrots                     | 1.0.0b1              | carrotslib-mc1.12.2-1.0.0b1.jar                    | None                                     |
	| LCHI  | armorunder                  | 1.0.0                | armorunder-mc1.12.2-1.0.0.jar                      | None                                     |
	| LCHI  | astikorcarts                | 1.12.2-0.1.2.7       | astikorcarts-1.12.2-0.1.2.7.jar                    | None                                     |
	| LCHI  | betteranimals               | 5.3.0                | betteranimals-1.12.2-5.3.0.jar                     | None                                     |
	| LCHI  | quark                       | r1.6-177             | Quark-r1.6-177.jar                                 | None                                     |
	| LCHI  | autoreglib                  | 1.3-32               | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCHI  | bannerelytra                | 1.0                  | bannerelytra-1.0.jar                               | None                                     |
	| LCHI  | basketcase                  | 1.0.31               | Basketcase-v1.0.31-mc1.12.2.jar                    | None                                     |
	| LCHI  | beasts                      | 1.2                  | Beasts-1.12.2-1.2.1.jar                            | None                                     |
	| LCHI  | betteranimalsplus           | 8.2.0                | betteranimalsplus-1.12.2-8.2.0.jar                 | None                                     |
	| LCHI  | bettercombatmod             | 1.5.6                | BetterCombat-1.12.2-1.5.6.jar                      | None                                     |
	| LCHI  | biomesoplenty               | 7.0.1.2444           | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar      | None                                     |
	| LCHI  | better_diving               | 1.4.14               | BetterDiving-1.12.2-1.4.14.jar                     | None                                     |
	| LCHI  | betterfoliage               | 2.3.1                | BetterFoliage-MC1.12-2.3.1.jar                     | None                                     |
	| LCHI  | betternether                | 0.1.8.6              | betternether-0.1.8.6.jar                           | None                                     |
	| LCHI  | blur                        | 1.0.4-14             | Blur-1.0.4-14.jar                                  | None                                     |
	| LCHI  | brazier                     | 1.2.0                | brazier-1.2.0.jar                                  | None                                     |
	| LCHI  | bmtr                        | 0.4                  | BringMeTheRings-0.4.jar                            | None                                     |
	| LCHI  | cd4017be_lib                | 6.4.17               | CD4017BE_lib-1.12.2-6.4.17.1.jar                   | None                                     |
	| LCHI  | sandro                      | 1.3d                 | Redstone++ ver1.3d.jar                             | None                                     |
	| LCHI  | redstoneplusplus            | 1.3d                 | Redstone++ ver1.3d.jar                             | None                                     |
	| LCHI  | charm                       | 1.12.2-1.3.6         | Charm-1.12.2-1.3.6.jar                             | None                                     |
	| LCHI  | llibrary                    | 1.7.19               | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHI  | cqrepoured                  | 1.10.0A              | ChocolateQuestRepoured-1.12.2-1.10.0A.jar          | None                                     |
	| LCHI  | colytra                     | 1.2.0.4              | colytra-1.12.2-1.2.0.4.jar                         | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHI  | comforts                    | 1.4.1.3              | comforts-1.12.2-1.4.1.3.jar                        | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHI  | controlling                 | 3.0.8                | Controlling-3.0.8.jar                              | None                                     |
	| LCHI  | crafttweaker                | 4.1.20               | CraftTweaker2-1.12-4.1.20.jar                      | None                                     |
	| LCHI  | cookingforblockheads        | 6.5.0                | CookingForBlockheads_1.12.2-6.5.0.jar              | None                                     |
	| LCHI  | configmod                   | v1.0                 | coroutil-1.12.1-1.2.36.jar                         | None                                     |
	| LCHI  | extendedrenderer            | v1.0                 | coroutil-1.12.1-1.2.36.jar                         | None                                     |
	| LCHI  | coroutil                    | 1.12.1-1.2.36        | coroutil-1.12.1-1.2.36.jar                         | None                                     |
	| LCHI  | cosmeticbeds                | 1.12.2-1.0.2.2       | cosmeticbeds-1.12.2-1.0.2.2.jar                    | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHI  | craftingtweaks              | 8.1.9                | CraftingTweaks_1.12.2-8.1.9.jar                    | None                                     |
	| LCHI  | craftstudioapi              | 1.0.0                | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCHI  | ctgui                       | 1.0.0                | CraftTweaker2-1.12-4.1.20.jar                      | None                                     |
	| LCHI  | crafttweakerjei             | 2.0.3                | CraftTweaker2-1.12-4.1.20.jar                      | None                                     |
	| LCHI  | creativecore                | 1.9.9                | CreativeCore_v1.9.90_mc1.12.2.jar                  | None                                     |
	| LCHI  | crimsonrevelations          | 0.6                  | crimsonrevelations-0.7.jar                         | None                                     |
	| LCHI  | crimsonwarfare              | 1.5                  | crimsonwarfare-1.5.jar                             | None                                     |
	| LCHI  | ctm                         | MC1.12.2-1.0.1.30    | CTM-MC1.12.2-1.0.1.30.jar                          | None                                     |
	| LCHI  | customcursormod             | 1.2.2                | CustomCursorMod-1.2.2.jar                          | None                                     |
	| LCHI  | customstartinggear          | 1.2.0                | CustomStartingGear-1.12-1.2.0.9-universal.jar      | None                                     |
	| LCHI  | cyclopscore                 | 1.6.1                | CyclopsCore-1.12.2-1.6.1.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHI  | debark                      | 0.1.2                | Debark-0.1.2.jar                                   | None                                     |
	| LCHI  | dynamiclights               | 1.4.9                | DynamicLights-1.12.2.jar                           | None                                     |
	| LCHI  | dynamiclights_onfire        | 1.0.7                | DynamicLights-1.12.2.jar                           | None                                     |
	| LCHI  | dynamiclights_creepers      | 1.0.6                | DynamicLights-1.12.2.jar                           | None                                     |
	| LCHI  | dynamiclights_dropitems     | 1.1.0                | DynamicLights-1.12.2.jar                           | None                                     |
	| LCHI  | dynamiclights_entityclasses | 1.0.1                | DynamicLights-1.12.2.jar                           | None                                     |
	| LCHI  | dynamiclights_mobequipment  | 1.1.0                | DynamicLights-1.12.2.jar                           | None                                     |
	| LCHI  | dynamiclights_flamearrows   | 1.0.1                | DynamicLights-1.12.2.jar                           | None                                     |
	| LCHI  | dynamiclights_floodlights   | 1.0.3                | DynamicLights-1.12.2.jar                           | None                                     |
	| LCHI  | dynamiclights_otherplayers  | 1.0.9                | DynamicLights-1.12.2.jar                           | None                                     |
	| LCHI  | dynamiclights_theplayer     | 1.1.3                | DynamicLights-1.12.2.jar                           | None                                     |
	| LCHI  | orelib                      | 3.6.0.1              | OreLib-1.12.2-3.6.0.1.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHI  | dsurround                   | 3.6.0.2              | DynamicSurroundings-1.12.2-3.6.0.2.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHI  | dynamictrees                | 1.12.2-0.9.7         | DynamicTrees-1.12.2-0.9.7.jar                      | None                                     |
	| LCHI  | dynamictreesbop             | 1.12.2-1.4.1e        | DynamicTreesBOP-1.12.2-1.4.1e.jar                  | None                                     |
	| LCHI  | harvestcraft                | 1.12.2zb             | Pam's HarvestCraft 1.12.2zf.jar                    | None                                     |
	| LCHI  | dynamictreesphc             | 1.12.2-1.4.2         | DynamicTreesPHC-1.12.2-1.4.2.jar                   | None                                     |
	| LCHI  | rustic                      | 1.1.2                | rustic-1.1.2.jar                                   | None                                     |
	| LCHI  | dynamictreestc              | 1.12.2-1.4.1e        | DynamicTreesTC-1.12.2-1.4.1e.jar                   | None                                     |
	| LCHE  | enchantedwolves             | 1.0                  | enchantedwolves-1.12.2-1.1.jar                     | None                                     |
	| LCH   | endercore                   | 1.12.2-0.5.74        | EnderCore-1.12.2-0.5.74.jar                        | None                                     |
	| LCH   | endreborn                   | 0.3.1                | EndReborn III [0.3.1].jar                          | None                                     |
	| LCH   | engineeredgolems            | 1.2                  | Engineered Golems-1.2a.jar                         | None                                     |
	| LCH   | engineersdoors              | 0.8.0                | engineers_doors-1.12.2-0.8.0.jar                   | None                                     |
	| LCH   | equipmenttooltips           | 1.0.3                | EquipmentTooltips-1.12.2-1.0.3-4.jar               | None                                     |
	| LCH   | ea                          | 1.0.1                | ExpandedArcanum-1.0.1.jar                          | None                                     |
	| LCH   | farseek                     | 2.4                  | Farseek-1.12-2.4.jar                               | None                                     |
	| LCH   | fivefeetsmall               | 1.0.1                | FiveFeetSmall-v1.0.1-1.12.2.jar                    | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
	| LCH   | foamfix                     | 0.10.10-1.12.2       | foamfix-0.10.10-1.12.2.jar                         | None                                     |
	| LCH   | friendlyfire                | 1.5.12               | FriendlyFire-1.12.2-1.5.12.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | geographicraft              | 0.8.7                | GeographiCraft-1.12-0.8.9b.jar                     | None                                     |
	| LCH   | hammercore                  | 2.0.6.13             | HammerCore-1.12.2-2.0.6.13.jar                     | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCH   | horsestandstill             | 1.12.2-0.0.1         | horsestandstill-1.12.2-0.0.1.jar                   | None                                     |
	| LCH   | horsestats                  | 1.0.1                | horsestats-1.12.2-1.0.1.jar                        | None                                     |
	| LCH   | horsetweaks                 | 1.0.5                | HorseTweaks_1.12.2-1.0.5.jar                       | None                                     |
	| LCH   | waila                       | 1.8.26               | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCH   | thaumadditions              | 12.2.4               | ThaumicAdditions-1.12.2-12.2.4.jar                 | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCH   | iceandfire                  | 1.8.4                | iceandfire-1.8.4.jar                               | None                                     |
	| LCH   | immersivehempcraft          | 1.12-0.0.7.1         | Immersive HempCraft-1.12-0.0.7.1.jar               | None                                     |
	| LCH   | immersivecables             | 1.3.2                | ImmersiveCables-1.12.2-1.3.2.jar                   | None                                     |
	| LCH   | immersivepetroleum          | 1.1.9                | immersivepetroleum-1.12.2-1.1.9.jar                | None                                     |
	| LCH   | immersiveposts              | 0.1.5                | ImmersivePosts-0.1.5.jar                           | 0ba8738eadcf158e7fe1452255a73a022fb15feb |
	| LCH   | trackapi                    | 1.2                  | TrackAPI-1.2.jar                                   | None                                     |
	| LCH   | immersiverailroading        | 1.7.2                | ImmersiveRailroading-1.7.2_1.12.2.jar              | None                                     |
	| LCH   | universalmodcore            | 1.0.0                | ImmersiveRailroading-1.7.2_1.12.2.jar              | None                                     |
	| LCH   | infernalmobs                | 1.7.6                | InfernalMobs-1.12.2.jar                            | None                                     |
	| LCH   | jaffa                       | 7.63.1               | JAFFA-7.63.1.jar                                   | None                                     |
	| LCH   | jeresources                 | 0.9.2.60             | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
	| LCH   | jeroreintegration           | 1.1.0                | JEROreIntegration-1.12.2-1.1.0.jar                 | None                                     |
	| LCH   | brewcraft                   | 1.12.2-1.0.1         | Pam's BrewCraft 1.12.2-1.0.1.jar                   | None                                     |
	| LCH   | jebc                        | 1.0.1                | just-enough-brewcraft-1.12.2-1.0.1.jar             | None                                     |
	| LCH   | jehc                        | 1.7.0                | just-enough-harvestcraft-1.12.2-1.7.0.jar          | None                                     |
	| LCH   | justenoughpetroleum         | 0.1                  | JustEnoughPetroleum-0.1.jar                        | None                                     |
	| LCH   | knowledgeshare              | 1.1                  | knowledgeshare-1.1.jar                             | None                                     |
	| LCH   | letmesleep                  | 1.2.1                | LetMeSleep-v1.2.1-1.12.2.jar                       | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
	| LCH   | dogslie                     | 1.0.2                | LetSleepingDogsLie-1.12.2-1.0.2.jar                | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | levelup2                    | ${version}           | levelup2-1.2.4.jar                                 | None                                     |
	| LCH   | libraryex                   | 1.0.12               | LibraryEx-1.12.2-1.0.12.jar                        | None                                     |
	| LCH   | livingenchantment           | 3.2.1                | living_enchantment-3.2.1.jar                       | None                                     |
	| LCH   | matchlockweapons            | 0.8                  | Matchlock Guns Mod-1.12.2-7a.jar                   | None                                     |
	| LCH   | immersivetech               | 1.7.47               | MCTImmersiveTechnology-1.12.2-1.7.47.jar           | None                                     |
	| LCH   | mysticalmechanics           | 0.12                 | Mystical Mechanics-0.12.jar                        | None                                     |
	| LCH   | mech_crafting               | 1.1.1                | MechanicalCrafting-1.1.1.jar                       | None                                     |
	| LCH   | tbone                       | v1.6.8+mc1.12.2      | TBone-v1.6.8+mc1.12.2.jar                          | None                                     |
	| LCH   | metalchests                 | v6.1.0+mc1.12.2      | MetalChests-v6.1.0+mc1.12.2.jar                    | None                                     |
	| LCH   | moarboats                   | 4.1.2.1              | moarboats-1.12.2-4.1.2.1.jar                       | None                                     |
	| LCH   | mountedpearl                | 1.0                  | mountedpearl-1.12.2-0.0.1.jar                      | None                                     |
	| LCH   | mousetweaks                 | 2.10                 | MouseTweaks-2.10-mc1.12.2.jar                      | None                                     |
	| LCH   | mowziesmobs                 | 1.5.4                | mowziesmobs-1.5.4.jar                              | None                                     |
	| LCH   | multimob                    | 1.0.5                | multimob-1.0.5.jar                                 | None                                     |
	| LCH   | thaumicperiphery            | 0.3.1                | thaumicperiphery-0.3.1.jar                         | None                                     |
	| LCH   | mystgears                   | 1.1.0                | mystgears-1.1.0.jar                                | None                                     |
	| LCH   | netherex                    | 2.0.15               | NetherEx-1.12.2-2.0.15.jar                         | None                                     |
	| LCH   | opencomputers               | 1.7.5.192            | OpenComputers-MC1.12.2-1.7.5.192.jar               | None                                     |
	| LCH   | outfox                      | 0.1.4                | outfox-0.1.4-mc1.12.2.jar                          | None                                     |
	| LCH   | pamscookables               | 1.1                  | pamscookables-1.1.jar                              | None                                     |
	| LCH   | parry                       | 1.0                  | parry-1.0-hotfix.jar                               | None                                     |
	| LCH   | patchouli                   | 1.0-20               | Patchouli-1.0-20.jar                               | None                                     |
	| LCH   | pathundergates              | 1.12.2-2.1.0-release | pathundergates-1.12.2-2.1.0-release.jar            | None                                     |
	| LCH   | placebo                     | 1.6.0                | Placebo-1.12.2-1.6.0.jar                           | None                                     |
	| LCH   | quarkoddities               | 1                    | QuarkOddities-1.12.2.jar                           | None                                     |
	| LCH   | rs_ctr                      | 0.2.6                | RedstoneControl-1.12.2-0.2.6.1.jar                 | None                                     |
	| LCH   | rusticthaumaturgy           | 4.4a                 | Rustic Thaumaturgy-4.4a.jar                        | None                                     |
	| LCH   | rusticbopwoods              | 1.0                  | rusticbopwoods-1.0.jar                             | None                                     |
	| LCH   | rustichromia                | 0.6                  | Rustichromia-0.6.jar                               | None                                     |
	| LCH   | silentlib                   | 3.0.13               | SilentLib-1.12.2-3.0.14+168.jar                    | None                                     |
	| LCH   | scalinghealth               | 1.3.37               | ScalingHealth-1.12.2-1.3.42+147.jar                | None                                     |
	| LCH   | scarper                     | 1.1                  | scarper-1.1.jar                                    | None                                     |
	| LCH   | signal_stuff                | 1.0.0                | SignalStuff_1.6.jar                                | None                                     |
	| LCH   | simpledifficulty            | 0.2.4                | SimpleDifficulty-1.12.2-0.2.4.jar                  | None                                     |
	| LCH   | sledgehammer                | 1.12.2-0.7-2.0.0     | Sledgehammer-1.12.2-0.7-2.0.0.jar                  | 565fa4dbf20e7c3c4423950ca8e0bdabf7568796 |
	| LCH   | spartanweaponry             | beta 1.3.8           | SpartanWeaponry-1.12.2-beta-1.3.8.jar              | None                                     |
	| LCH   | spartanfire                 | 0.07                 | spartanfire-0.07.jar                               | None                                     |
	| LCH   | spartanshields              | 1.5.4                | SpartanShields-1.12.2-1.5.4.jar                    | None                                     |
	| LCH   | spartanweaponryarcana       | beta 1.0.3           | SpartanWeaponryArcana-1.12.2-beta-1.0.3.jar        | None                                     |
	| LCH   | stg                         | 1.12.2-1.2.3         | stg-1.12.2-1.2.3.jar                               | None                                     |
	| LCH   | stygian                     | 1.0.4                | stygian-1.0.4.jar                                  | None                                     |
	| LCH   | surge                       | 2.0.77               | Surge-1.12.2-2.0.77.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | swordblockingcombat         | 1.0.2                | SwordBlockingCombat-v1.0.2-1.12.2.jar              | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
	| LCH   | tenshilib                   | 1.2.3                | TenshiLib-1.12.2-1.2.3.jar                         | None                                     |
	| LCH   | thaumicaugmentation         | 1.12.2-1.1.17        | ThaumicAugmentation-1.12.2-1.1.17.jar              | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
	| LCH   | thaumicbrewing              | 1.0.2                | thaumicbrewing-1.0.2.jar                           | None                                     |
	| LCH   | thaumcomp                   | 0.5.1                | ThaumicComputers-MC1.12.2-0.5.1.jar                | None                                     |
	| LCH   | tcinventoryscan             | 2.0.10               | ThaumicInventoryScanning_1.12.2-2.0.10.jar         | None                                     |
	| LCH   | thaumicjei                  | 1.6.0                | ThaumicJEI-1.12.2-1.6.0-27.jar                     | None                                     |
	| LCH   | thaumicwaila                | 1.12.2-0.0.1         | ThaumicWaila-1.12.2-0.0.1.jar                      | None                                     |
	| LCH   | tipthescales                | 1.0.4                | TipTheScales-1.12.2-1.0.4.jar                      | None                                     |
	| LCH   | toastcontrol                | 1.8.1                | Toast Control-1.12.2-1.8.1.jar                     | None                                     |
	| LCH   | travellersbackpack          | 1.0.22.22            | TravellersBackpack-1.12.2-1.0.22.22.jar            | None                                     |
	| LCH   | walljump                    | 1.3.2                | walljump-1.12.2-1.3.2.jar                          | None                                     |
	| LCH   | wawla                       | 2.6.274              | Wawla-1.12.2-2.6.274.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | wearablebackpacks           | 3.1.4                | WearableBackpacks-1.12.2-3.1.4.jar                 | None                                     |
	| LCH   | wolfarmor                   | 3.3.0.279            | wolfarmor-1.12.2-3.3.0.279-SNAPSHOT-all.jar        | None                                     |
	| LCH   | xaerominimap                | 20.2.0               | Xaeros_Minimap_FP20.2.0_Forge_1.12.jar             | None                                     |
	| LCH   | xaeroworldmap               | 1.5.5                | XaerosWorldMap_1.5.5_Forge_1.12.jar                | None                                     |
	| LCH   | zerocore                    | 1.12.2-0.1.2.8       | zerocore-1.12.2-0.1.2.8.jar                        | None                                     |
	| LCH   | jade                        | 0.1.0                | Jade-0.1.0.jar                                     | None                                     |
	| LCH   | phosphor-lighting           | 1.12.2-0.2.6         | phosphor-1.12.2-0.2.6+build50-universal.jar        | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCH   | snowrealmagic               | 0.3.3                | SnowRealMagic-0.3.3.jar                            | None                                     |

	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-1.1.17.jar)
  thecodex6824.thaumicaugmentation.core.TATransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
  
HCASM (HammerCore-1.12.2-2.0.6.13.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
ColytraLoadingPlugin (colytra-1.12.2-1.2.0.4.jar)
  c4.colytra.asm.ElytraTransformer
iceandfire (iceandfire-1.8.4.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.74-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
BringMeTheRings plugin (BringMeTheRings-0.4.jar)
  zabi.minecraft.bmtr.core.BaublesTransformer
SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  
WolfArmorCore (wolfarmor-1.12.2-3.3.0.279-SNAPSHOT-all.jar)
  
CharmLoadingPlugin (Charm-1.12.2-1.3.6.jar)
  svenhjol.charm.base.CharmClassTransformer
CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  
TenshiCore (TenshiLib-1.12.2-1.2.3.jar)
  com.flemmli97.tenshilib.asm.ASMTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
RandomPatches (randompatches-1.12.2-1.21.0.0.jar)
  com.therandomlabs.randompatches.core.RPTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
FarseekCoreMod (Farseek-1.12-2.4.jar)
  farseek.core.FarseekClassTransformer
DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 431.60' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	HammerCore Debug Information: 
Dependent Mods:
    -Thaumic Additions: Reconstructed (thaumadditions) @12.2.4
20:47:26.328
STDOUT
Client thread
[net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Mizhok\Twitch\Minecraft\Instances\IE and Myst Mech\crash-reports\crash-2020-02-25_20.47.26-client.txt```

**Comment by Mizhok** [comment]
Wrong mod, whoops
